import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  String _lang = 'en';
  String get lang => _lang;

  static const Map<String, String> languages = {
    'en': 'English',
    'si': 'සිංහල',
    'ta': 'தமிழ்',
  };

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _lang = prefs.getString('language') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _lang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
    notifyListeners();
  }

  String t(String key) => _translations[_lang]?[key] ?? _translations['en']?[key] ?? key;

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // App general
      'app_name': 'AgriSense LK',
      'app_tagline': 'Agricultural Intelligence Platform',
      // Auth
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'create_account': 'Create Account',
      'join_title': 'Join AgriSense LK',
      'join_sub': 'Create your account to get started',
      'email': 'Email Address',
      'password': 'Password',
      'username': 'Username',
      'user_type': 'User Type',
      'already_account': 'Already have an account?',
      'no_account': "Don't have an account?",
      'farmer': 'Farmer',
      'buyer': 'Buyer',
      'trader': 'Trader',
      'researcher': 'Researcher',
      // Home
      'welcome_back': 'Welcome back',
      'predict_today': 'What would you like to predict today?',
      'ai_features': 'AI Features',
      'predict': 'Predict',
      'view_history': 'View History',
      'my_profile': 'My Profile',
      // Features
      'price_demand': 'Price & Demand',
      'price_demand_sub': 'Predict crop prices and market demand',
      'market_ranking': 'Market Ranking',
      'market_ranking_sub': 'Find best markets for your crops',
      'cultivation': 'Cultivation Targeting',
      'cultivation_sub': 'Optimal crop cultivation recommendations',
      'yield_quality': 'Yield & Quality',
      'yield_quality_sub': 'Analyze crop yield and quality grade',
      'profitable_strategy': 'Profitable Strategy',
      'profitable_strategy_sub': 'Business strategy recommendations',
      // Buttons
      'get_recommendations': 'Get Recommendations',
      'find_markets': 'Find Best Markets',
      'analyze': 'Analyze Yield & Quality',
      'get_strategy': 'Get Profitable Strategy',
      'predict_price': 'Predict Price & Demand',
      'back': 'Back to Predictions',
      // Forms
      'category': 'Category',
      'market': 'Market',
      'season': 'Season',
      'province': 'Province',
      'district': 'District',
      'crop_type': 'Crop Type',
      'soil_type': 'Soil Type',
      'rainfall': 'Annual Rainfall (mm)',
      'temperature': 'Average Temperature (°C)',
      'land_area': 'Land Area (acres)',
      'budget': 'Available Budget (Rs.)',
      'quantity': 'Quantity (kg)',
      'price': 'Price (Rs.)',
      'best_price': 'Best Unit Price (Rs. per kg)',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'upload_info': 'Upload crop images for AI quality grading (Grade A, B, C or Rotten)',
      // Results
      'prediction_complete': 'Prediction Complete!',
      'processed': 'AI model processed your data successfully.',
      'key_results': 'Key Results',
      'details': 'Details',
      // History & Profile
      'history': 'Prediction History',
      'profile': 'My Profile',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'version': 'App Version',
      'platform': 'Platform',
      'backend': 'Backend',
      'export_history': 'Export History',
    },
    'si': {
      'app_name': 'AgriSense LK',
      'app_tagline': 'කෘෂිකාර්මික බුද්ධිමත් වේදිකාව',
      'sign_in': 'ඇතුල් වන්න',
      'sign_up': 'ලියාපදිංචි වන්න',
      'create_account': 'ගිණුම සාදන්න',
      'join_title': 'AgriSense LK හා එකතු වන්න',
      'join_sub': 'ආරම්භ කිරීමට ඔබේ ගිණුම සාදන්න',
      'email': 'විද්‍යුත් තැපැල් ලිපිනය',
      'password': 'මුරපදය',
      'username': 'පරිශීලක නාමය',
      'user_type': 'පරිශීලක වර්ගය',
      'already_account': 'දැනටමත් ගිණුමක් තිබේද?',
      'no_account': 'ගිණුමක් නැද්ද?',
      'farmer': 'ගොවියා',
      'buyer': 'ගැනුම්කරු',
      'trader': 'වෙළෙඳුන්',
      'researcher': 'පර්යේෂකයා',
      'welcome_back': 'නැවත සාදරයෙන් පිළිගනිමු',
      'predict_today': 'අද ඔබ කුමක් පුරෝකථනය කිරීමට කැමතිද?',
      'ai_features': 'AI විශේෂාංග',
      'predict': 'පුරෝකථනය',
      'view_history': 'ඉතිහාසය බලන්න',
      'my_profile': 'මගේ පැතිකඩ',
      'price_demand': 'මිල සහ ඉල්ලුම',
      'price_demand_sub': 'බෝග මිල සහ වෙළඳපල ඉල්ලුම පුරෝකථනය',
      'market_ranking': 'වෙළඳපල ශ්‍රේණිගත කිරීම',
      'market_ranking_sub': 'ඔබේ බෝග සඳහා හොඳම වෙළඳපල සොයන්න',
      'cultivation': 'වගා ඉලක්කය',
      'cultivation_sub': 'ප්‍රශස්ත බෝග වගා නිර්දේශ',
      'yield_quality': 'අස්වනු සහ ගුණත්වය',
      'yield_quality_sub': 'බෝග අස්වනු සහ ගුණත්ව ශ්‍රේණිය විශ්ලේෂණය',
      'profitable_strategy': 'ලාභදායී උපාය',
      'profitable_strategy_sub': 'ව්‍යාපාර උපාය නිර්දේශ',
      'get_recommendations': 'නිර්දේශ ලබාගන්න',
      'find_markets': 'හොඳම වෙළඳපල සොයන්න',
      'analyze': 'අස්වනු සහ ගුණත්වය විශ්ලේෂණය',
      'get_strategy': 'ලාභදායී උපාය ලබාගන්න',
      'predict_price': 'මිල සහ ඉල්ලුම පුරෝකථනය',
      'back': 'පුරෝකථනවලට ආපසු',
      'category': 'කාණ්ඩය',
      'market': 'වෙළඳපල',
      'season': 'ඍතුව',
      'province': 'පළාත',
      'district': 'දිස්ත්‍රික්කය',
      'crop_type': 'බෝගයේ වර්ගය',
      'soil_type': 'පස් වර්ගය',
      'rainfall': 'වාර්ෂික වර්ෂාපතනය (mm)',
      'temperature': 'සාමාන්‍ය උෂ්ණත්වය (°C)',
      'land_area': 'ඉඩම් ප්‍රමාණය (අක්කර)',
      'budget': 'ලබාගත හැකි අයවැය (රු.)',
      'quantity': 'ප්‍රමාණය (kg)',
      'price': 'මිල (රු.)',
      'best_price': 'හොඳම ඒකක මිල (රු. kg කට)',
      'gallery': 'ගැලරිය',
      'camera': 'කැමරාව',
      'upload_info': 'AI ගුණත්ව ශ්‍රේණිගත කිරීම සඳහා බෝග රූප උඩුගත කරන්න',
      'prediction_complete': 'පුරෝකථනය සම්පූර්ණයි!',
      'processed': 'AI මාදිලිය ඔබේ දත්ත සාර්ථකව සකසා ඇත.',
      'key_results': 'ප්‍රධාන ප්‍රතිඵල',
      'details': 'විස්තර',
      'history': 'පුරෝකථන ඉතිහාසය',
      'profile': 'මගේ පැතිකඩ',
      'logout': 'ලොග් අවුට්',
      'logout_confirm': 'ඔබට නිසැකවම ලොග් අවුට් වීමට අවශ්‍යද?',
      'cancel': 'අවලංගු කරන්න',
      'version': 'යෙදුම් අනුවාදය',
      'platform': 'වේදිකාව',
      'backend': 'පසුපස',
      'export_history': 'ඉතිහාසය අපනයනය',
    },
    'ta': {
      'app_name': 'AgriSense LK',
      'app_tagline': 'விவசாய நுண்ணறிவு தளம்',
      'sign_in': 'உள்நுழைக',
      'sign_up': 'பதிவு செய்க',
      'create_account': 'கணக்கை உருவாக்கு',
      'join_title': 'AgriSense LK இல் சேரவும்',
      'join_sub': 'தொடங்க உங்கள் கணக்கை உருவாக்கவும்',
      'email': 'மின்னஞ்சல் முகவரி',
      'password': 'கடவுச்சொல்',
      'username': 'பயனர் பெயர்',
      'user_type': 'பயனர் வகை',
      'already_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'no_account': 'கணக்கு இல்லையா?',
      'farmer': 'விவசாயி',
      'buyer': 'வாங்குபவர்',
      'trader': 'வணிகர்',
      'researcher': 'ஆராய்ச்சியாளர்',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'predict_today': 'இன்று என்ன கணிக்க விரும்புகிறீர்கள்?',
      'ai_features': 'AI அம்சங்கள்',
      'predict': 'கணிக்க',
      'view_history': 'வரலாற்றை காண்க',
      'my_profile': 'என் சுயவிவரம்',
      'price_demand': 'விலை & தேவை',
      'price_demand_sub': 'பயிர் விலைகள் மற்றும் சந்தை தேவை கணிப்பு',
      'market_ranking': 'சந்தை தரவரிசை',
      'market_ranking_sub': 'உங்கள் பயிர்களுக்கு சிறந்த சந்தைகளை கண்டறியவும்',
      'cultivation': 'பயிர் இலக்கு',
      'cultivation_sub': 'உகந்த பயிர் சாகுபடி பரிந்துரைகள்',
      'yield_quality': 'மகசூல் & தரம்',
      'yield_quality_sub': 'பயிர் மகசூல் மற்றும் தர தரவரிசை பகுப்பாய்வு',
      'profitable_strategy': 'லாபகரமான மூலோபாயம்',
      'profitable_strategy_sub': 'வணிக மூலோபாய பரிந்துரைகள்',
      'get_recommendations': 'பரிந்துரைகளை பெறுக',
      'find_markets': 'சிறந்த சந்தைகளை கண்டறியவும்',
      'analyze': 'மகசூல் & தரத்தை பகுப்பாய்வு செய்க',
      'get_strategy': 'லாபகரமான மூலோபாயம் பெறுக',
      'predict_price': 'விலை & தேவை கணிக்க',
      'back': 'கணிப்புகளுக்கு திரும்பு',
      'category': 'வகை',
      'market': 'சந்தை',
      'season': 'பருவம்',
      'province': 'மாகாணம்',
      'district': 'மாவட்டம்',
      'crop_type': 'பயிர் வகை',
      'soil_type': 'மண் வகை',
      'rainfall': 'வருடாந்திர மழைப்பொழிவு (mm)',
      'temperature': 'சராசரி வெப்பநிலை (°C)',
      'land_area': 'நில பரப்பளவு (ஏக்கர்)',
      'budget': 'கிடைக்கக்கூடிய பட்ஜெட் (ரூ.)',
      'quantity': 'அளவு (kg)',
      'price': 'விலை (ரூ.)',
      'best_price': 'சிறந்த யூனிட் விலை (ரூ. kg க்கு)',
      'gallery': 'கேலரி',
      'camera': 'கேமரா',
      'upload_info': 'AI தர தரவரிசைக்கு பயிர் படங்களை பதிவேற்றவும்',
      'prediction_complete': 'கணிப்பு நிறைவடைந்தது!',
      'processed': 'AI மாதிரி உங்கள் தரவை வெற்றிகரமாக செயலாக்கியது.',
      'key_results': 'முக்கிய முடிவுகள்',
      'details': 'விவரங்கள்',
      'history': 'கணிப்பு வரலாறு',
      'profile': 'என் சுயவிவரம்',
      'logout': 'வெளியேறு',
      'logout_confirm': 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'cancel': 'ரத்துசெய்',
      'version': 'பயன்பாட்டு பதிப்பு',
      'platform': 'தளம்',
      'backend': 'பின்தளம்',
      'export_history': 'வரலாற்றை ஏற்றுமதி செய்க',
    },
  };
}
