import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  /// Static accessor for L10n compatibility
  static LanguageService get instance => _instance;

  String _lang = 'en';
  String get lang => _lang;

  static const Map<String, String> languages = {
    'en': 'English',
    'si': 'සිංහල',
    'ta': 'தமிழ்',
  };

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _lang = prefs.getString('language') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String lang) async {
    _lang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', lang);
    notifyListeners();
  }

  String t(String key) => _translations[_lang]?[key] ?? _translations['en']?[key] ?? key;

  // ═══════════════════════════════════════════════════════════════════════════
  //  TRANSLATIONS
  // ═══════════════════════════════════════════════════════════════════════════
  static const Map<String, Map<String, String>> _translations = {
    // ────────────────────────────────────────────────────────────────────────
    'en': {
      // App
      'app_name':    'AgriSense LK',
      'app_tagline': 'Agricultural Intelligence Platform',

      // Common
      'clear':             'Clear',
      'reset':             'Reset',
      'loading':           'Loading...',
      'required':          'Required',
      'back':              'Back to Predictions',
      'cancel':            'Cancel',
      'use_my_location':   'Use My Location',
      'locating':          'Locating…',
      'latitude':          'Latitude',
      'longitude':         'Longitude',
      'select_role':       'Select Role',
      'analyzing':         'Analyzing…',
      'retry':             'Retry',

      // Auth
      'sign_in':          'Sign In',
      'sign_up':          'Sign Up',
      'create_account':   'Create Account',
      'join_title':       'Join AgriSense LK',
      'join_sub':         'Create your account to get started',
      'email':            'Email Address',
      'password':         'Password',
      'username':         'Username',
      'user_type':        'User Type',
      'already_account':  'Already have an account?',
      'no_account':       "Don't have an account?",
      'farmer':           'Farmer',
      'buyer':            'Buyer',
      'seller':           'Seller',
      'trader':           'Trader',
      'researcher':       'Researcher',
      'welcome_back':     'Welcome back',
      'sign_in_sub':      'Sign in to your AgriSense account',
      'create_acct_sub':  'Create your account',
      'account_info':     'Account info',
      'security':         'Security',
      'i_am_a':           'I am a',
      'confirm_password':  'Confirm Password',
      'creating_acct':    'Creating account…',
      'signing_in':       'Signing in…',
      'register':         'Register',

      // Home
      'home':               'Home',
      'predict_today':      'What would you like to predict today?',
      'ai_features':        'AI FEATURES',
      'quick_access':       'QUICK ACCESS',
      'predict':            'Predict',
      'view_history':       'View History',
      'my_profile':         'My Profile',
      'logout':             'Logout',
      'logout_confirm':     'Are you sure you want to logout?',

      // Feature cards
      'price_demand':         'Price & Demand',
      'price_demand_sub':     'Predict crop prices and market demand',
      'market_ranking':       'Market Ranking',
      'market_ranking_sub':   'Find best markets for your crops',
      'cultivation':          'Cultivation Targeting',
      'cultivation_sub':      'Optimal crop cultivation recommendations',
      'yield_quality':        'Yield & Quality',
      'yield_quality_sub':    'Analyze crop yield and quality grade',
      'profitable_strategy':  'Profitable Strategy',
      'profitable_strategy_sub': 'Business strategy recommendations',

      // Price & Demand
      'pd_title':            'Price & Demand Prediction',
      'pd_product_info':     'Product Information',
      'pd_date_info':        'Date Information',
      'pd_hist_stats':       'Historical Statistics',
      'pd_market_cond':      'Market Conditions',
      'pd_item':             'Item',
      'pd_origin_type':      'Origin Type',
      'pd_price_type':       'Price Type',
      'pd_prev_price':       'Previous Price (Rs.)',
      'pd_year':             'Year',
      'pd_month':            'Month',
      'pd_day':              'Day',
      'pd_day_of_week':      'Day of Week',
      'pd_week_num':         'Week Number',
      'pd_quarter':          'Quarter',
      'pd_rolling_7':        '7-Day Rolling Mean (Rs.)',
      'pd_std_7':            '7-Day Std Dev (Rs.)',
      'pd_rolling_3':        '3-Day Rolling Mean (Rs.)',
      'pd_volatility':       'Volatility Index',
      'pd_sentiment':        'Market Sentiment',
      'pd_supply':           'Supply Status',
      'pd_predict_btn':      'Predict Price & Demand',
      'pd_predicting':       'Predicting…',
      'pd_result_title':     'Price & Demand Result',

      // Cultivation Targeting
      'ct_title':            'Cultivation Targeting',
      'ct_card':             'Cultivation Parameters',
      'ct_location':         'LOCATION',
      'ct_location_info':    'Enter coordinates for accurate weather-based recommendations.',
      'ct_core_params':      'CORE PARAMETERS',
      'ct_field_cond':       'FIELD CONDITIONS',
      'ct_month':            'Month *',
      'ct_category':         'Category *',
      'ct_risk':             'Risk Tolerance *',
      'ct_prev_profit':      'Previous Profitability (%)',
      'ct_prev_hint':        'Your average profitability from previous crops',
      'ct_budget':           'Available Budget (Rs.)',
      'ct_budget_hint':      'Your cultivation budget for the season',
      'ct_land_size':        'Land Size (Acres)',
      'ct_water':            'Water Availability',
      'ct_soil':             'Soil Type',
      'ct_get_rec':          'Get Recommendations',
      'ct_analyzing':        'Analyzing…',
      'ct_result_title':     'Cultivation Recommendations',
      'ct_lat_hint':         'e.g. 7.75 for central Sri Lanka',
      'ct_lon_hint':         'e.g. 80.75 for central Sri Lanka',
      'ct_res_weather':      'CURRENT WEATHER',
      'ct_res_humidity':     'Humidity',
      'ct_res_wind':         'Wind Speed',
      'ct_res_precip':       'Precipitation',
      'ct_res_soil_temp':    'Soil Temp',
      'ct_res_impact':       'CULTIVATION IMPACT',
      'ct_res_rec_summary':  'Recommendation Summary',
      'ct_res_season':       'Season',
      'ct_res_crops_rec':    'crops recommended',
      'ct_res_top_pick':     'TOP PICK',
      'ct_res_profitability':'Profitability',
      'ct_res_risk':         'Risk Score',
      'ct_res_avg_profit':   'Avg. Profitability',
      'ct_res_avg_risk':     'Avg. Risk',
      'ct_res_weather_tips': 'Weather-Adjusted Tips',
      'ct_res_all_crops':    'All Crop Recommendations',
      'ct_res_timeline':     'Timeline',
      'ct_res_revenue':      'Revenue',
      'ct_res_risk_level':   'Risk Level',
      'ct_res_forecast':     '7-Day Weather Forecast',
      'ct_res_date':         'DATE',
      'ct_res_max':          'MAX',
      'ct_res_min':          'MIN',
      'ct_res_wind_col':     'WIND',
      'ct_res_cond':         'CONDITIONS',
      'ct_res_insights':     'FORECAST INSIGHTS',

      // Market Ranking
      'mr_title':           'Market Opportunity Ranking',
      'mr_card':            'Market Search Parameters',
      'mr_role_section':    'ROLE SELECTION',
      'mr_cost_section':    'COST INFORMATION',
      'mr_item_section':    'TARGET ITEM & QUANTITY',
      'mr_your_location':   'YOUR LOCATION',
      'mr_gps_coords':      'GPS COORDINATES',
      'mr_transport':       'Transport Cost (Rs.)',
      'mr_add_transport':   'Additional Transport Cost (Rs.)',
      'mr_cult_cost':       'Cultivation Cost (Rs.)',
      'mr_ref_price':       'Reference Price (Rs.)',
      'mr_item':            'Item *',
      'mr_price_type':      'Price Type',
      'mr_quantity':        'Quantity',
      'mr_unit':            'Unit',
      'mr_find':            'Find Best Markets',
      'mr_reset':           'Clear / Reset',
      'mr_result_title':    'Market Rankings',
      'mr_select_item':     'Select Item',
      'mr_formula_default': '📋 Select your role to see the calculation formula',
      'mr_formula_seller':  '💡 Seller formula: Revenue − (Cultivation Cost + Transport Cost)',
      'mr_formula_buyer':   '💡 Buyer formula: Reference Cost − (Price × Qty + Transport Cost)',
      'mr_select_role_err': 'Please select your role',
      'mr_select_item_err': 'Please select an item',
      'mr_res_top_recs':    'Top Recommendations',
      'mr_res_best_market': 'BEST MARKET',
      'mr_res_analyzed':    'markets analyzed',
      'mr_res_price':       'Price',
      'mr_res_distance':    'Distance',
      'mr_res_transport':   'Transport',
      'mr_res_net_rev':     'Net Revenue',
      'mr_res_all_recs':    'All Market Recommendations',
      'mr_res_avg_price':   'Avg. Price',
      'mr_res_avg_dist':    'Avg. Distance',
      'mr_res_qty':         'Quantity Analyzed',
      'mr_res_map':         'Market Locations Map',
      'mr_res_explanation': 'Explanation',

      // Profitable Strategy
      'ps_title':           'Profitable Strategy',
      'ps_card1':           'Profile, Family & Financial Info',
      'ps_card2':           'Cultivation Targeting',
      'ps_card3':           'Market Information',
      'ps_card4':           'Location Information',
      'ps_sec_profile':     'PROFILE & PURPOSE',
      'ps_sec_financial':   'FINANCIAL INFORMATION',
      'ps_role':            'Role',
      'ps_profession':      'Profession',
      'ps_purpose':         'Purpose',
      'ps_income':          'Monthly Income (Rs.)',
      'ps_income_source':   'Income Source',
      'ps_budget_source':   'Budget Source',
      'ps_fetch_cult':      'Fetch from Cultivation',
      'ps_fetch_market':    'Fetch from Market',
      'ps_cult_item':       'Cultivation Item',
      'ps_optimal_month':   'Optimal Month',
      'ps_season':          'Season',
      'ps_cult_profit':     'Cultivation Profitability (%)',
      'ps_cult_risk':       'Cultivation Risk (%)',
      'ps_market_item':     'Market Item',
      'ps_market_name':     'Market Name',
      'ps_pred_price':      'Predicted Price (Rs./kg)',
      'ps_distance':        'Distance (km)',
      'ps_transport':       'Transport Cost (Rs.)',
      'ps_net_adv':         'Net Advantage (Rs.)',
      'ps_get_strategy':    'Get Profitable Strategy',
      'ps_analyzing':       'Analyzing…',
      'ps_result_title':    'Profitable Strategy',
      'ps_loc_hint':        'Enter coordinates or use GPS to auto-fill location.',
      'ps_res_ai_rec':      'AI RECOMMENDATION',
      'ps_res_confidence':  'Confidence',
      'ps_res_risk_level':  'Risk Level',
      'ps_res_capital':     'Capital Required',
      'ps_res_biz_code':    'Business Code',
      'ps_res_description': 'Description',
      'ps_res_consider':    'Key Considerations',
      'ps_res_challenges':  'Potential Challenges',
      'ps_res_alternatives':'Alternative Options',
      'ps_res_conf_dist':   'Confidence Distribution',

      // Yield & Quality
      'yq_title':           'Yield & Quality Analysis',
      'yq_info':            'Upload crop images for AI quality grading — Grade A, B, C or Rotten.',
      'yq_pricing':         'Pricing',
      'yq_price_label':     'Best Unit Price (Rs. per kg) *',
      'yq_images':          'Crop Images',
      'yq_no_images':       'No images selected',
      'yq_tap_hint':        'Tap Gallery or Camera above',
      'yq_camera_web':      'Camera not available on web — use Gallery.',
      'yq_analyze':         'Analyze Yield & Quality',
      'yq_analyzing':       'Analyzing Images…',
      'yq_result_title':    'Yield & Quality Result',
      'yq_images_count':    'image(s) selected',
      'yq_enter_price':     'Enter price',

      // Yield Quality Result
      'yq_res_title':         'Prediction Results',
      'yq_res_subtitle':      'AI grading complete',
      'yq_res_images_analyzed':'images analysed',
      'yq_res_grade_header':  'Overall Predicted Grade',
      'yq_res_confidence':    'Confidence',
      'yq_res_timestamp':     'Timestamp',
      'yq_res_img_count':     'Images',
      'yq_res_avg_conf':      'Avg. Confidence',
      'yq_res_mean_prob':     'Mean Probability',
      'yq_res_market_rate':   'Market Rate',
      'yq_res_per_kg':        '/ kg',
      'yq_res_pred_price':    'Predicted Unit Price',
      'yq_res_img_results':   'Individual Image Results',
      'yq_res_image':         'Image',
      'yq_res_grade':         'Grade',
      'yq_grade_a':           'Premium Quality',
      'yq_grade_b':           'Good Quality',
      'yq_grade_c':           'Average Quality',
      'yq_grade_rotten':      'Below Standard',

      // History
      'hist_title':         'Prediction History',
      'hist_header':        'Your Prediction History',
      'hist_saved':         'All your past predictions are saved here',
      'hist_view_full':     'View Full History',
      'hist_view_sub':      'Open detailed history with filters and export',
      'hist_export':        'Export History',

      // Profile
      'profile_title':      'My Profile',
      'profile_about':      'About App',
      'profile_version':    'App Version',
      'profile_platform':   'Platform',
      'profile_backend':    'Backend',
      'profile_username':   'Username',
      'profile_email':      'Email',
      'profile_type':       'User Type',

      // Forms
      'category':           'Category',
      'market':             'Market',
      'season':             'Season',
      'province':           'Province',
      'district':           'District',
      'ds_division':        'DS Division',
      'crop_type':          'Crop Type',
      'soil_type':          'Soil Type',
      'budget':             'Available Budget (Rs.)',
      'quantity':           'Quantity (kg)',
      'price':              'Price (Rs.)',
      'best_price':         'Best Unit Price (Rs. per kg)',
      'gallery':            'Gallery',
      'camera':             'Camera',
      'select_province':    'Select Province',
      'select_district':    'Select District',
      'select_ds':          'Select DS Division',
      'province_first':     'Select Province first',
      'district_first':     'Select District first',

      // Buttons
      'get_recommendations': 'Get Recommendations',
      'find_markets':        'Find Best Markets',
      'analyze':             'Analyze Yield & Quality',
      'get_strategy':        'Get Profitable Strategy',
      'predict_price':       'Predict Price & Demand',
      'version':             'App Version',
      'platform':            'Platform',
      'backend':             'Backend',
      'export_history':      'Export History',
    },

    // ────────────────────────────────────────────────────────────────────────
    'si': {
      // App
      'app_name':    'AgriSense LK',
      'app_tagline': 'කෘෂිකාර්මික බුද්ධිමත් වේදිකාව',

      // Common
      'clear':             'මකන්න',
      'reset':             'යළි සකසන්න',
      'loading':           'පූරණය වෙමින්...',
      'required':          'අවශ්‍යයි',
      'back':              'පුරෝකථනවලට ආපසු',
      'cancel':            'අවලංගු කරන්න',
      'use_my_location':   'මගේ ස්ථානය භාවිතා කරන්න',
      'locating':          'ස්ථානය සොයමින්…',
      'latitude':          'අක්ෂාංශ',
      'longitude':         'දේශාංශ',
      'select_role':       'භූමිකාව තෝරන්න',
      'analyzing':         'විශ්ලේෂණය කරමින්…',
      'retry':             'නැවත උත්සාහ කරන්න',

      // Auth
      'sign_in':          'ඇතුල් වන්න',
      'sign_up':          'ලියාපදිංචි වන්න',
      'create_account':   'ගිණුම සාදන්න',
      'join_title':       'AgriSense LK හා එකතු වන්න',
      'join_sub':         'ආරම්භ කිරීමට ඔබේ ගිණුම සාදන්න',
      'email':            'විද්‍යුත් තැපැල් ලිපිනය',
      'password':         'මුරපදය',
      'username':         'පරිශීලක නාමය',
      'user_type':        'පරිශීලක වර්ගය',
      'already_account':  'දැනටමත් ගිණුමක් තිබේද?',
      'no_account':       'ගිණුමක් නැද්ද?',
      'farmer':           'ගොවියා',
      'buyer':            'ගැනුම්කරු',
      'seller':           'විකුණුම්කරු',
      'trader':           'වෙළෙඳුන්',
      'researcher':       'පර්යේෂකයා',
      'welcome_back':     'නැවත සාදරයෙන් පිළිගනිමු',
      'sign_in_sub':      'ඔබේ AgriSense ගිණුමට ඇතුල් වන්න',
      'create_acct_sub':  'ඔබේ ගිණුම සාදන්න',
      'account_info':     'ගිණුම් තොරතුරු',
      'security':         'ආරක්ෂාව',
      'i_am_a':           'මම',
      'confirm_password':  'මුරපදය තහවුරු කරන්න',
      'creating_acct':    'ගිණුම සාදමින්…',
      'signing_in':       'ඇතුල් වෙමින්…',
      'register':         'ලියාපදිංචි වන්න',

      // Home
      'home':               'මුල් පිටුව',
      'predict_today':      'අද ඔබ කුමක් පුරෝකථනය කිරීමට කැමතිද?',
      'ai_features':        'AI විශේෂාංග',
      'quick_access':       'ඉක්මන් ප්‍රවේශය',
      'predict':            'පුරෝකථනය',
      'view_history':       'ඉතිහාසය බලන්න',
      'my_profile':         'මගේ පැතිකඩ',
      'logout':             'ලොග් අවුට්',
      'logout_confirm':     'ඔබට නිසැකවම ලොග් අවුට් වීමට අවශ්‍යද?',

      // Feature cards
      'price_demand':         'මිල සහ ඉල්ලුම',
      'price_demand_sub':     'බෝග මිල සහ වෙළඳපල ඉල්ලුම පුරෝකථනය',
      'market_ranking':       'වෙළඳපල ශ්‍රේණිගත කිරීම',
      'market_ranking_sub':   'ඔබේ බෝග සඳහා හොඳම වෙළඳපල සොයන්න',
      'cultivation':          'වගා ඉලක්ක කිරීම',
      'cultivation_sub':      'ප්‍රශස්ත බෝග වගා නිර්දේශ',
      'yield_quality':        'අස්වනු සහ ගුණත්වය',
      'yield_quality_sub':    'බෝග අස්වනු සහ ගුණත්ව ශ්‍රේණිය විශ්ලේෂණය',
      'profitable_strategy':  'ලාභදායී උපාය',
      'profitable_strategy_sub': 'ව්‍යාපාර උපාය නිර්දේශ',

      // Price & Demand
      'pd_title':            'මිල සහ ඉල්ලුම පුරෝකථනය',
      'pd_product_info':     'නිෂ්පාදන තොරතුරු',
      'pd_date_info':        'දිනය තොරතුරු',
      'pd_hist_stats':       'ඓතිහාසික සංඛ්‍යාලේඛන',
      'pd_market_cond':      'වෙළඳපල තත්ත්ව',
      'pd_item':             'භාණ්ඩය',
      'pd_origin_type':      'මූලාරම්භ වර්ගය',
      'pd_price_type':       'මිල වර්ගය',
      'pd_prev_price':       'පෙර මිල (රු.)',
      'pd_year':             'වර්ෂය',
      'pd_month':            'මාසය',
      'pd_day':              'දිනය',
      'pd_day_of_week':      'සතියේ දිනය',
      'pd_week_num':         'සතිය අංකය',
      'pd_quarter':          'කාර්තුව',
      'pd_rolling_7':        'දින 7 රෝලිං සාමාන්‍යය (රු.)',
      'pd_std_7':            'දින 7 ප්‍රමිතික අපගමනය (රු.)',
      'pd_rolling_3':        'දින 3 රෝලිං සාමාන්‍යය (රු.)',
      'pd_volatility':       'අස්ථිරතා දර්ශකය',
      'pd_sentiment':        'වෙළඳපල හැඟීම',
      'pd_supply':           'සැපයුම් තත්ත්වය',
      'pd_predict_btn':      'මිල සහ ඉල්ලුම පුරෝකථනය',
      'pd_predicting':       'පුරෝකථනය කරමින්…',
      'pd_result_title':     'මිල සහ ඉල්ලුම ප්‍රතිඵල',

      // Cultivation Targeting
      'ct_title':            'වගා ඉලක්ක කිරීම',
      'ct_card':             'වගා පරාමිතිය',
      'ct_location':         'ස්ථානය',
      'ct_location_info':    'නිවැරදි කාලගුණ පදනම් නිර්දේශ සඳහා ඛණ්ඩාංක ඇතුළු කරන්න.',
      'ct_core_params':      'මූලික පරාමිතිය',
      'ct_field_cond':       'ක්ෂේත්‍ර තත්ත්ව',
      'ct_month':            'මාසය *',
      'ct_category':         'කාණ්ඩය *',
      'ct_risk':             'අවදානම් ඉවසීම *',
      'ct_prev_profit':      'පෙර ලාභදායීතාව (%)',
      'ct_prev_hint':        'ඔබේ පෙර බෝගවලින් සාමාන්‍ය ලාභදායීතාව',
      'ct_budget':           'ලබාගත හැකි අයවැය (රු.)',
      'ct_budget_hint':      'ඍතුවේ ඔබේ වගා අයවැය',
      'ct_land_size':        'ඉඩම් ප්‍රමාණය (අක්කර)',
      'ct_water':            'ජල ලබා ගැනීමේ හැකියාව',
      'ct_soil':             'පස් වර්ගය',
      'ct_get_rec':          'නිර්දේශ ලබාගන්න',
      'ct_analyzing':        'විශ්ලේෂණය කරමින්…',
      'ct_result_title':     'වගා නිර්දේශ',
      'ct_lat_hint':         'උ.දා. 7.75 මධ්‍යම ශ්‍රී ලංකාව සඳහා',
      'ct_lon_hint':         'උ.දා. 80.75 මධ්‍යම ශ්‍රී ලංකාව සඳහා',
      'ct_res_weather':      'වත්මන් කාලගුණය',
      'ct_res_humidity':     'ආර්ද්‍රතාව',
      'ct_res_wind':         'සුළං වේගය',
      'ct_res_precip':       'වර්ෂාපතනය',
      'ct_res_soil_temp':    'පස් උෂ්ණත්වය',
      'ct_res_impact':       'වගා බලපෑම',
      'ct_res_rec_summary':  'නිර්දේශ සාරාංශය',
      'ct_res_season':       'ඍතුව',
      'ct_res_crops_rec':    'බෝග නිර්දේශිතයි',
      'ct_res_top_pick':     'ඉහළ තේරීම',
      'ct_res_profitability':'ලාභදායීතාව',
      'ct_res_risk':         'අවදානම් ලකුණු',
      'ct_res_avg_profit':   'සාමාන්‍ය ලාභදායීතාව',
      'ct_res_avg_risk':     'සාමාන්‍ය අවදානම',
      'ct_res_weather_tips': 'කාලගුණ ඉඟි',
      'ct_res_all_crops':    'සියලු බෝග නිර්දේශ',
      'ct_res_timeline':     'කාල රේඛාව',
      'ct_res_revenue':      'ආදායම',
      'ct_res_risk_level':   'අවදානම් මට්ටම',
      'ct_res_forecast':     'දින 7 කාලගුණ අනාවැකිය',
      'ct_res_date':         'දිනය',
      'ct_res_max':          'උපරිම',
      'ct_res_min':          'අවම',
      'ct_res_wind_col':     'සුළං',
      'ct_res_cond':         'තත්ත්වය',
      'ct_res_insights':     'අනාවැකි තොරතුරු',

      // Market Ranking
      'mr_title':           'වෙළඳපල අවස්ථා ශ්‍රේණිගත කිරීම',
      'mr_card':            'වෙළඳපල සෙවීමේ පරාමිතිය',
      'mr_role_section':    'භූමිකාව තෝරීම',
      'mr_cost_section':    'පිරිවැය තොරතුරු',
      'mr_item_section':    'ඉලක්ක භාණ්ඩය සහ ප්‍රමාණය',
      'mr_your_location':   'ඔබේ ස්ථානය',
      'mr_gps_coords':      'GPS ඛණ්ඩාංක',
      'mr_transport':       'ප්‍රවාහන පිරිවැය (රු.)',
      'mr_add_transport':   'අතිරේක ප්‍රවාහන පිරිවැය (රු.)',
      'mr_cult_cost':       'වගා පිරිවැය (රු.)',
      'mr_ref_price':       'යොමු මිල (රු.)',
      'mr_item':            'භාණ්ඩය *',
      'mr_price_type':      'මිල වර්ගය',
      'mr_quantity':        'ප්‍රමාණය',
      'mr_unit':            'ඒකකය',
      'mr_find':            'හොඳම වෙළඳපල සොයන්න',
      'mr_reset':           'ඉවත් කරන්න / යළි සකසන්න',
      'mr_result_title':    'වෙළඳපල ශ්‍රේණිගත කිරීම්',
      'mr_select_item':     'භාණ්ඩය තෝරන්න',
      'mr_formula_default': '📋 ගණනය කිරීමේ සූත්‍රය බැලීමට ඔබේ භූමිකාව තෝරන්න',
      'mr_formula_seller':  '💡 විකුණුම්කරු සූත්‍රය: ආදායම − (වගා පිරිවැය + ප්‍රවාහන පිරිවැය)',
      'mr_formula_buyer':   '💡 ගැනුම්කරු සූත්‍රය: යොමු පිරිවැය − (මිල × ප්‍රමාණය + ප්‍රවාහන පිරිවැය)',
      'mr_select_role_err': 'ඔබේ භූමිකාව තෝරන්න',
      'mr_select_item_err': 'භාණ්ඩය තෝරන්න',
      'mr_res_top_recs':    'ඉහළ නිර්දේශ',
      'mr_res_best_market': 'හොඳම වෙළඳපල',
      'mr_res_analyzed':    'වෙළඳපල විශ්ලේෂණය',
      'mr_res_price':       'මිල',
      'mr_res_distance':    'දුර',
      'mr_res_transport':   'ප්‍රවාහනය',
      'mr_res_net_rev':     'ශුද්ධ ආදායම',
      'mr_res_all_recs':    'සියලු වෙළඳපල නිර්දේශ',
      'mr_res_avg_price':   'සාමාන්‍ය මිල',
      'mr_res_avg_dist':    'සාමාන්‍ය දුර',
      'mr_res_qty':         'විශ්ලේෂිත ප්‍රමාණය',
      'mr_res_map':         'වෙළඳපල ස්ථාන සිතියම',
      'mr_res_explanation': 'පැහැදිලි කිරීම',

      // Profitable Strategy
      'ps_title':           'ලාභදායී උපාය',
      'ps_card1':           'පැතිකඩ, පවුල සහ මූල්‍ය තොරතුරු',
      'ps_card2':           'වගා ඉලක්ක කිරීම',
      'ps_card3':           'වෙළඳපල තොරතුරු',
      'ps_card4':           'ස්ථාන තොරතුරු',
      'ps_sec_profile':     'පැතිකඩ සහ අරමුණ',
      'ps_sec_financial':   'මූල්‍ය තොරතුරු',
      'ps_role':            'භූමිකාව',
      'ps_profession':      'වෘත්තිය',
      'ps_purpose':         'අරමුණ',
      'ps_income':          'මාසික ආදායම (රු.)',
      'ps_income_source':   'ආදායම් මූලාශ්‍රය',
      'ps_budget_source':   'අයවැය මූලාශ්‍රය',
      'ps_fetch_cult':      'වගාවෙන් ලබාගන්න',
      'ps_fetch_market':    'වෙළඳපලෙන් ලබාගන්න',
      'ps_cult_item':       'වගා භාණ්ඩය',
      'ps_optimal_month':   'ප්‍රශස්ත මාසය',
      'ps_season':          'ඍතුව',
      'ps_cult_profit':     'වගා ලාභදායීතාව (%)',
      'ps_cult_risk':       'වගා අවදානම (%)',
      'ps_market_item':     'වෙළඳපල භාණ්ඩය',
      'ps_market_name':     'වෙළඳපල නාමය',
      'ps_pred_price':      'අනාවැකි මිල (රු./kg)',
      'ps_distance':        'දුර (km)',
      'ps_transport':       'ප්‍රවාහන පිරිවැය (රු.)',
      'ps_net_adv':         'ශුද්ධ වාසිය (රු.)',
      'ps_get_strategy':    'ලාභදායී උපාය ලබාගන්න',
      'ps_analyzing':       'විශ්ලේෂණය කරමින්…',
      'ps_result_title':    'ලාභදායී උපාය',
      'ps_loc_hint':        'ස්ථානය ස්වයංක්‍රීයව පිරවීමට ඛණ්ඩාංක ඇතුළු කරන්න හෝ GPS භාවිතා කරන්න.',
      'ps_res_ai_rec':      'AI නිර්දේශය',
      'ps_res_confidence':  'විශ්වාසය',
      'ps_res_risk_level':  'අවදානම් මට්ටම',
      'ps_res_capital':     'අවශ්‍ය ප්‍රාග්ධනය',
      'ps_res_biz_code':    'ව්‍යාපාර කේතය',
      'ps_res_description': 'විස්තරය',
      'ps_res_consider':    'ප්‍රධාන සලකා බැලීම්',
      'ps_res_challenges':  'සිදුවිය හැකි අභියෝග',
      'ps_res_alternatives':'විකල්ප විකල්ප',
      'ps_res_conf_dist':   'විශ්වාස බෙදාහැරීම',

      // Yield & Quality
      'yq_title':           'අස්වනු සහ ගුණත්ව විශ්ලේෂණය',
      'yq_info':            'AI ගුණත්ව ශ්‍රේණිගත කිරීම සඳහා බෝග රූප උඩුගත කරන්න — A, B, C හෝ කොළ.',
      'yq_pricing':         'මිල ගණන',
      'yq_price_label':     'හොඳම ඒකක මිල (රු. kg කට) *',
      'yq_images':          'බෝග රූප',
      'yq_no_images':       'රූප තෝරා නැත',
      'yq_tap_hint':        'ගැලරිය හෝ කැමරාව ඉහළින් තෝරන්න',
      'yq_camera_web':      'වෙබ් මත කැමරාව ලබා නොගත හැක — ගැලරිය භාවිතා කරන්න.',
      'yq_analyze':         'අස්වනු සහ ගුණත්වය විශ්ලේෂණය',
      'yq_analyzing':       'රූප විශ්ලේෂණය කරමින්…',
      'yq_result_title':    'අස්වනු සහ ගුණත්ව ප්‍රතිඵල',
      'yq_images_count':    'රූප(ය/ය) තෝරා ගෙන ඇත',
      'yq_enter_price':     'මිල ඇතුළු කරන්න',

      // Yield Quality Result
      'yq_res_title':         'පුරෝකථන ප්‍රතිඵල',
      'yq_res_subtitle':      'AI ශ්‍රේණිගත කිරීම සම්පූර්ණයි',
      'yq_res_images_analyzed':'රූප විශ්ලේෂණය',
      'yq_res_grade_header':  'සමස්ත පුරෝකථන ශ්‍රේණිය',
      'yq_res_confidence':    'විශ්වාසය',
      'yq_res_timestamp':     'කාල මුද්‍රාව',
      'yq_res_img_count':     'රූප',
      'yq_res_avg_conf':      'සාමාන්‍ය විශ්වාසය',
      'yq_res_mean_prob':     'සාමාන්‍ය සම්භාවිතාව',
      'yq_res_market_rate':   'වෙළඳ මිල',
      'yq_res_per_kg':        '/ kg',
      'yq_res_pred_price':    'පුරෝකථන ඒකක මිල',
      'yq_res_img_results':   'තනි රූප ප්‍රතිඵල',
      'yq_res_image':         'රූපය',
      'yq_res_grade':         'ශ්‍රේණිය',
      'yq_grade_a':           'ඉහළ ගුණත්වය',
      'yq_grade_b':           'හොඳ ගුණත්වය',
      'yq_grade_c':           'සාමාන්‍ය ගුණත්වය',
      'yq_grade_rotten':      'පහළ ප්‍රමාණය',

      // History
      'hist_title':         'පුරෝකථන ඉතිහාසය',
      'hist_header':        'ඔබේ පුරෝකථන ඉතිහාසය',
      'hist_saved':         'ඔබේ සියලු පෙර පුරෝකථන මෙහි සුරකින ලදී',
      'hist_view_full':     'සම්පූර්ණ ඉතිහාසය බලන්න',
      'hist_view_sub':      'පෙරීමෙන් සහ අපනයනය සහිත විස්තරාත්මක ඉතිහාසය',
      'hist_export':        'ඉතිහාසය අපනයනය',

      // Profile
      'profile_title':      'මගේ පැතිකඩ',
      'profile_about':      'යෙදුම ගැන',
      'profile_version':    'යෙදුම් අනුවාදය',
      'profile_platform':   'වේදිකාව',
      'profile_backend':    'පසුපස',
      'profile_username':   'පරිශීලක නාමය',
      'profile_email':      'විද්‍යුත් තැපෑල',
      'profile_type':       'පරිශීලක වර්ගය',

      // Forms
      'category':           'කාණ්ඩය',
      'market':             'වෙළඳපල',
      'season':             'ඍතුව',
      'province':           'පළාත',
      'district':           'දිස්ත්‍රික්කය',
      'ds_division':        'DS කොට්ඨාශය',
      'crop_type':          'බෝගයේ වර්ගය',
      'soil_type':          'පස් වර්ගය',
      'budget':             'ලබාගත හැකි අයවැය (රු.)',
      'quantity':           'ප්‍රමාණය (kg)',
      'price':              'මිල (රු.)',
      'best_price':         'හොඳම ඒකක මිල (රු. kg කට)',
      'gallery':            'ගැලරිය',
      'camera':             'කැමරාව',
      'select_province':    'පළාත තෝරන්න',
      'select_district':    'දිස්ත්‍රික්කය තෝරන්න',
      'select_ds':          'DS කොට්ඨාශය තෝරන්න',
      'province_first':     'පළාත පළමුව තෝරන්න',
      'district_first':     'දිස්ත්‍රික්කය පළමුව තෝරන්න',

      // Buttons
      'get_recommendations': 'නිර්දේශ ලබාගන්න',
      'find_markets':        'හොඳම වෙළඳපල සොයන්න',
      'analyze':             'අස්වනු සහ ගුණත්වය විශ්ලේෂණය',
      'get_strategy':        'ලාභදායී උපාය ලබාගන්න',
      'predict_price':       'මිල සහ ඉල්ලුම පුරෝකථනය',
      'version':             'යෙදුම් අනුවාදය',
      'platform':            'වේදිකාව',
      'backend':             'පසුපස',
      'export_history':      'ඉතිහාසය අපනයනය',
    },

    // ────────────────────────────────────────────────────────────────────────
    'ta': {
      // App
      'app_name':    'AgriSense LK',
      'app_tagline': 'விவசாய நுண்ணறிவு தளம்',

      // Common
      'clear':             'அழிக்க',
      'reset':             'மீட்டமைக்க',
      'loading':           'ஏற்றுகிறது...',
      'required':          'தேவை',
      'back':              'கணிப்புகளுக்கு திரும்பு',
      'cancel':            'ரத்துசெய்',
      'use_my_location':   'என் இடத்தை பயன்படுத்து',
      'locating':          'இடம் கண்டறிகிறது…',
      'latitude':          'அட்சரேகை',
      'longitude':         'தீர்க்கரேகை',
      'select_role':       'பங்கை தேர்ந்தெடுக்கவும்',
      'analyzing':         'பகுப்பாய்வு செய்கிறது…',
      'retry':             'மீண்டும் முயற்சிக்கவும்',

      // Auth
      'sign_in':          'உள்நுழைக',
      'sign_up':          'பதிவு செய்க',
      'create_account':   'கணக்கை உருவாக்கு',
      'join_title':       'AgriSense LK இல் சேரவும்',
      'join_sub':         'தொடங்க உங்கள் கணக்கை உருவாக்கவும்',
      'email':            'மின்னஞ்சல் முகவரி',
      'password':         'கடவுச்சொல்',
      'username':         'பயனர் பெயர்',
      'user_type':        'பயனர் வகை',
      'already_account':  'ஏற்கனவே கணக்கு உள்ளதா?',
      'no_account':       'கணக்கு இல்லையா?',
      'farmer':           'விவசாயி',
      'buyer':            'வாங்குபவர்',
      'seller':           'விற்பவர்',
      'trader':           'வணிகர்',
      'researcher':       'ஆராய்ச்சியாளர்',
      'welcome_back':     'மீண்டும் வரவேற்கிறோம்',
      'sign_in_sub':      'உங்கள் AgriSense கணக்கில் உள்நுழைக',
      'create_acct_sub':  'உங்கள் கணக்கை உருவாக்கவும்',
      'account_info':     'கணக்கு தகவல்',
      'security':         'பாதுகாப்பு',
      'i_am_a':           'நான் ஒரு',
      'confirm_password':  'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'creating_acct':    'கணக்கு உருவாக்குகிறது…',
      'signing_in':       'உள்நுழைகிறது…',
      'register':         'பதிவு செய்க',

      // Home
      'home':               'முகப்பு',
      'predict_today':      'இன்று என்ன கணிக்க விரும்புகிறீர்கள்?',
      'ai_features':        'AI அம்சங்கள்',
      'quick_access':       'விரைவு அணுகல்',
      'predict':            'கணிக்க',
      'view_history':       'வரலாற்றை காண்க',
      'my_profile':         'என் சுயவிவரம்',
      'logout':             'வெளியேறு',
      'logout_confirm':     'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',

      // Feature cards
      'price_demand':         'விலை & தேவை',
      'price_demand_sub':     'பயிர் விலைகள் மற்றும் சந்தை தேவை கணிப்பு',
      'market_ranking':       'சந்தை தரவரிசை',
      'market_ranking_sub':   'உங்கள் பயிர்களுக்கு சிறந்த சந்தைகளை கண்டறியவும்',
      'cultivation':          'பயிர் இலக்கீடு',
      'cultivation_sub':      'உகந்த பயிர் சாகுபடி பரிந்துரைகள்',
      'yield_quality':        'மகசூல் & தரம்',
      'yield_quality_sub':    'பயிர் மகசூல் மற்றும் தர தரவரிசை பகுப்பாய்வு',
      'profitable_strategy':  'லாபகரமான மூலோபாயம்',
      'profitable_strategy_sub': 'வணிக மூலோபாய பரிந்துரைகள்',

      // Price & Demand
      'pd_title':            'விலை & தேவை கணிப்பு',
      'pd_product_info':     'தயாரிப்பு தகவல்',
      'pd_date_info':        'தேதி தகவல்',
      'pd_hist_stats':       'வரலாற்று புள்ளிவிவரங்கள்',
      'pd_market_cond':      'சந்தை நிலைமைகள்',
      'pd_item':             'பொருள்',
      'pd_origin_type':      'தோற்றம் வகை',
      'pd_price_type':       'விலை வகை',
      'pd_prev_price':       'முந்தைய விலை (ரூ.)',
      'pd_year':             'ஆண்டு',
      'pd_month':            'மாதம்',
      'pd_day':              'நாள்',
      'pd_day_of_week':      'வார நாள்',
      'pd_week_num':         'வார எண்',
      'pd_quarter':          'காலாண்டு',
      'pd_rolling_7':        '7-நாள் உருட்டும் சராசரி (ரூ.)',
      'pd_std_7':            '7-நாள் நிலையான விலகல் (ரூ.)',
      'pd_rolling_3':        '3-நாள் உருட்டும் சராசரி (ரூ.)',
      'pd_volatility':       'ஏற்ற இறக்க குறியீடு',
      'pd_sentiment':        'சந்தை உணர்வு',
      'pd_supply':           'விநியோக நிலை',
      'pd_predict_btn':      'விலை & தேவை கணிக்க',
      'pd_predicting':       'கணிக்கிறது…',
      'pd_result_title':     'விலை & தேவை முடிவு',

      // Cultivation Targeting
      'ct_title':            'பயிர் இலக்கீடு',
      'ct_card':             'சாகுபடி அளவுருக்கள்',
      'ct_location':         'இடம்',
      'ct_location_info':    'துல்லியமான வானிலை அடிப்படையிலான பரிந்துரைகளுக்கு ஆயத்தொலைவுகளை உள்ளிடவும்.',
      'ct_core_params':      'மையமான அளவுருக்கள்',
      'ct_field_cond':       'வயல் நிலைமைகள்',
      'ct_month':            'மாதம் *',
      'ct_category':         'வகை *',
      'ct_risk':             'இடர் சகிப்புத்தன்மை *',
      'ct_prev_profit':      'முந்தைய லாபம் (%)',
      'ct_prev_hint':        'உங்கள் முந்தைய பயிர்களிலிருந்து சராசரி லாபம்',
      'ct_budget':           'கிடைக்கக்கூடிய பட்ஜெட் (ரூ.)',
      'ct_budget_hint':      'பருவத்திற்கான உங்கள் சாகுபடி பட்ஜெட்',
      'ct_land_size':        'நில அளவு (ஏக்கர்)',
      'ct_water':            'நீர் கிடைக்கும் தன்மை',
      'ct_soil':             'மண் வகை',
      'ct_get_rec':          'பரிந்துரைகளை பெறுக',
      'ct_analyzing':        'பகுப்பாய்வு செய்கிறது…',
      'ct_result_title':     'சாகுபடி பரிந்துரைகள்',
      'ct_lat_hint':         'எ.கா. 7.75 மத்திய இலங்கைக்கு',
      'ct_lon_hint':         'எ.கா. 80.75 மத்திய இலங்கைக்கு',
      'ct_res_weather':      'தற்போதைய வானிலை',
      'ct_res_humidity':     'ஈரப்பதம்',
      'ct_res_wind':         'காற்று வேகம்',
      'ct_res_precip':       'மழைவீழ்ச்சி',
      'ct_res_soil_temp':    'மண் வெப்பநிலை',
      'ct_res_impact':       'சாகுபடி தாக்கம்',
      'ct_res_rec_summary':  'பரிந்துரை சுருக்கம்',
      'ct_res_season':       'பருவம்',
      'ct_res_crops_rec':    'பயிர்கள் பரிந்துரைக்கப்பட்டன',
      'ct_res_top_pick':     'சிறந்த தேர்வு',
      'ct_res_profitability':'லாபம்',
      'ct_res_risk':         'இடர் மதிப்பெண்',
      'ct_res_avg_profit':   'சராசரி லாபம்',
      'ct_res_avg_risk':     'சராசரி இடர்',
      'ct_res_weather_tips': 'வானிலை குறிப்புகள்',
      'ct_res_all_crops':    'அனைத்து பயிர் பரிந்துரைகள்',
      'ct_res_timeline':     'காலவரிசை',
      'ct_res_revenue':      'வருவாய்',
      'ct_res_risk_level':   'இடர் நிலை',
      'ct_res_forecast':     '7-நாள் வானிலை முன்னறிவிப்பு',
      'ct_res_date':         'தேதி',
      'ct_res_max':          'அதிகபட்சம்',
      'ct_res_min':          'குறைந்தபட்சம்',
      'ct_res_wind_col':     'காற்று',
      'ct_res_cond':         'நிலைமைகள்',
      'ct_res_insights':     'முன்னறிவிப்பு நுண்ணறிவு',

      // Market Ranking
      'mr_title':           'சந்தை வாய்ப்பு தரவரிசை',
      'mr_card':            'சந்தை தேடல் அளவுருக்கள்',
      'mr_role_section':    'பங்கு தேர்வு',
      'mr_cost_section':    'செலவு தகவல்',
      'mr_item_section':    'இலக்கு பொருள் & அளவு',
      'mr_your_location':   'உங்கள் இடம்',
      'mr_gps_coords':      'GPS ஆயத்தொலைவுகள்',
      'mr_transport':       'போக்குவரத்து செலவு (ரூ.)',
      'mr_add_transport':   'கூடுதல் போக்குவரத்து செலவு (ரூ.)',
      'mr_cult_cost':       'சாகுபடி செலவு (ரூ.)',
      'mr_ref_price':       'குறிப்பு விலை (ரூ.)',
      'mr_item':            'பொருள் *',
      'mr_price_type':      'விலை வகை',
      'mr_quantity':        'அளவு',
      'mr_unit':            'அலகு',
      'mr_find':            'சிறந்த சந்தைகளை கண்டறியவும்',
      'mr_reset':           'அழிக்க / மீட்டமைக்க',
      'mr_result_title':    'சந்தை தரவரிசைகள்',
      'mr_select_item':     'பொருளை தேர்ந்தெடுக்கவும்',
      'mr_formula_default': '📋 கணக்கீட்டு சூத்திரம் காண உங்கள் பங்கை தேர்ந்தெடுக்கவும்',
      'mr_formula_seller':  '💡 விற்பவர் சூத்திரம்: வருவாய் − (சாகுபடி செலவு + போக்குவரத்து செலவு)',
      'mr_formula_buyer':   '💡 வாங்குபவர் சூத்திரம்: குறிப்பு செலவு − (விலை × அளவு + போக்குவரத்து செலவு)',
      'mr_select_role_err': 'உங்கள் பங்கை தேர்ந்தெடுக்கவும்',
      'mr_select_item_err': 'பொருளை தேர்ந்தெடுக்கவும்',
      'mr_res_top_recs':    'சிறந்த பரிந்துரைகள்',
      'mr_res_best_market': 'சிறந்த சந்தை',
      'mr_res_analyzed':    'சந்தைகள் பகுப்பாய்வு',
      'mr_res_price':       'விலை',
      'mr_res_distance':    'தூரம்',
      'mr_res_transport':   'போக்குவரத்து',
      'mr_res_net_rev':     'நிகர வருவாய்',
      'mr_res_all_recs':    'அனைத்து சந்தை பரிந்துரைகள்',
      'mr_res_avg_price':   'சராசரி விலை',
      'mr_res_avg_dist':    'சராசரி தூரம்',
      'mr_res_qty':         'பகுப்பாய்வு செய்த அளவு',
      'mr_res_map':         'சந்தை இட வரைபடம்',
      'mr_res_explanation': 'விளக்கம்',

      // Profitable Strategy
      'ps_title':           'லாபகரமான மூலோபாயம்',
      'ps_card1':           'சுயவிவரம், குடும்பம் & நிதி தகவல்',
      'ps_card2':           'பயிர் இலக்கீடு',
      'ps_card3':           'சந்தை தகவல்',
      'ps_card4':           'இட தகவல்',
      'ps_sec_profile':     'சுயவிவரம் & நோக்கம்',
      'ps_sec_financial':   'நிதி தகவல்',
      'ps_role':            'பங்கு',
      'ps_profession':      'தொழில்',
      'ps_purpose':         'நோக்கம்',
      'ps_income':          'மாதாந்திர வருமானம் (ரூ.)',
      'ps_income_source':   'வருமான மூலம்',
      'ps_budget_source':   'பட்ஜெட் மூலம்',
      'ps_fetch_cult':      'சாகுபடியிலிருந்து பெறுக',
      'ps_fetch_market':    'சந்தையிலிருந்து பெறுக',
      'ps_cult_item':       'சாகுபடி பொருள்',
      'ps_optimal_month':   'உகந்த மாதம்',
      'ps_season':          'பருவம்',
      'ps_cult_profit':     'சாகுபடி லாபம் (%)',
      'ps_cult_risk':       'சாகுபடி இடர் (%)',
      'ps_market_item':     'சந்தை பொருள்',
      'ps_market_name':     'சந்தை பெயர்',
      'ps_pred_price':      'கணிக்கப்பட்ட விலை (ரூ./kg)',
      'ps_distance':        'தூரம் (km)',
      'ps_transport':       'போக்குவரத்து செலவு (ரூ.)',
      'ps_net_adv':         'நிகர நன்மை (ரூ.)',
      'ps_get_strategy':    'லாபகரமான மூலோபாயம் பெறுக',
      'ps_analyzing':       'பகுப்பாய்வு செய்கிறது…',
      'ps_result_title':    'லாபகரமான மூலோபாயம்',
      'ps_loc_hint':        'இடத்தை தானாக நிரப்ப ஆயத்தொலைவுகளை உள்ளிடவும் அல்லது GPS பயன்படுத்தவும்.',
      'ps_res_ai_rec':      'AI பரிந்துரை',
      'ps_res_confidence':  'நம்பகத்தன்மை',
      'ps_res_risk_level':  'இடர் நிலை',
      'ps_res_capital':     'தேவையான மூலதனம்',
      'ps_res_biz_code':    'வணிக குறியீடு',
      'ps_res_description': 'விவரம்',
      'ps_res_consider':    'முக்கிய கருத்தில் கொள்ள வேண்டியவை',
      'ps_res_challenges':  'சாத்தியமான சவால்கள்',
      'ps_res_alternatives':'மாற்று விருப்பங்கள்',
      'ps_res_conf_dist':   'நம்பகத்தன்மை விநியோகம்',

      // Yield & Quality
      'yq_title':           'மகசூல் & தர பகுப்பாய்வு',
      'yq_info':            'AI தர தரவரிசைக்கு பயிர் படங்களை பதிவேற்றவும் — A, B, C தரம் அல்லது அழுகல்.',
      'yq_pricing':         'விலை நிர்ணயம்',
      'yq_price_label':     'சிறந்த யூனிட் விலை (ரூ. kg க்கு) *',
      'yq_images':          'பயிர் படங்கள்',
      'yq_no_images':       'படங்கள் தேர்ந்தெடுக்கப்படவில்லை',
      'yq_tap_hint':        'மேலே கேலரி அல்லது கேமரா தட்டவும்',
      'yq_camera_web':      'வலையில் கேமரா கிடைக்கவில்லை — கேலரி பயன்படுத்தவும்.',
      'yq_analyze':         'மகசூல் & தரத்தை பகுப்பாய்வு செய்க',
      'yq_analyzing':       'படங்களை பகுப்பாய்வு செய்கிறது…',
      'yq_result_title':    'மகசூல் & தர முடிவு',
      'yq_images_count':    'படம்/படங்கள் தேர்ந்தெடுக்கப்பட்டன',
      'yq_enter_price':     'விலை உள்ளிடவும்',

      // Yield Quality Result
      'yq_res_title':         'கணிப்பு முடிவுகள்',
      'yq_res_subtitle':      'AI தர வரிசை முடிந்தது',
      'yq_res_images_analyzed':'படங்கள் பகுப்பாய்வு',
      'yq_res_grade_header':  'ஒட்டுமொத்த கணிக்கப்பட்ட தரம்',
      'yq_res_confidence':    'நம்பகத்தன்மை',
      'yq_res_timestamp':     'நேர முத்திரை',
      'yq_res_img_count':     'படங்கள்',
      'yq_res_avg_conf':      'சராசரி நம்பகத்தன்மை',
      'yq_res_mean_prob':     'சராசரி நிகழ்தகவு',
      'yq_res_market_rate':   'சந்தை விலை',
      'yq_res_per_kg':        '/ kg',
      'yq_res_pred_price':    'கணிக்கப்பட்ட யூனிட் விலை',
      'yq_res_img_results':   'தனிப்பட்ட படம் முடிவுகள்',
      'yq_res_image':         'படம்',
      'yq_res_grade':         'தரம்',
      'yq_grade_a':           'உயர்தர தரம்',
      'yq_grade_b':           'நல்ல தரம்',
      'yq_grade_c':           'சராசரி தரம்',
      'yq_grade_rotten':      'தரமற்றது',

      // History
      'hist_title':         'கணிப்பு வரலாறு',
      'hist_header':        'உங்கள் கணிப்பு வரலாறு',
      'hist_saved':         'உங்கள் அனைத்து முந்தைய கணிப்புகளும் இங்கே சேமிக்கப்பட்டுள்ளன',
      'hist_view_full':     'முழு வரலாற்றை காண்க',
      'hist_view_sub':      'வடிகட்டிகள் மற்றும் ஏற்றுமதியுடன் விரிவான வரலாறு',
      'hist_export':        'வரலாற்றை ஏற்றுமதி செய்க',

      // Profile
      'profile_title':      'என் சுயவிவரம்',
      'profile_about':      'பயன்பாட்டு பற்றி',
      'profile_version':    'பயன்பாட்டு பதிப்பு',
      'profile_platform':   'தளம்',
      'profile_backend':    'பின்தளம்',
      'profile_username':   'பயனர் பெயர்',
      'profile_email':      'மின்னஞ்சல்',
      'profile_type':       'பயனர் வகை',

      // Forms
      'category':           'வகை',
      'market':             'சந்தை',
      'season':             'பருவம்',
      'province':           'மாகாணம்',
      'district':           'மாவட்டம்',
      'ds_division':        'DS பிரிவு',
      'crop_type':          'பயிர் வகை',
      'soil_type':          'மண் வகை',
      'budget':             'கிடைக்கக்கூடிய பட்ஜெட் (ரூ.)',
      'quantity':           'அளவு (kg)',
      'price':              'விலை (ரூ.)',
      'best_price':         'சிறந்த யூனிட் விலை (ரூ. kg க்கு)',
      'gallery':            'கேலரி',
      'camera':             'கேமரா',
      'select_province':    'மாகாணம் தேர்ந்தெடுக்கவும்',
      'select_district':    'மாவட்டம் தேர்ந்தெடுக்கவும்',
      'select_ds':          'DS பிரிவு தேர்ந்தெடுக்கவும்',
      'province_first':     'முதலில் மாகாணம் தேர்ந்தெடுக்கவும்',
      'district_first':     'முதலில் மாவட்டம் தேர்ந்தெடுக்கவும்',

      // Buttons
      'get_recommendations': 'பரிந்துரைகளை பெறுக',
      'find_markets':        'சிறந்த சந்தைகளை கண்டறியவும்',
      'analyze':             'மகசூல் & தரத்தை பகுப்பாய்வு செய்க',
      'get_strategy':        'லாபகரமான மூலோபாயம் பெறுக',
      'predict_price':       'விலை & தேவை கணிக்க',
      'version':             'பயன்பாட்டு பதிப்பு',
      'platform':            'தளம்',
      'backend':             'பின்தளம்',
      'export_history':      'வரலாற்றை ஏற்றுமதி செய்க',
    },
  };
}

// ── Mixin that rebuilds a StatefulWidget when language changes ─────────────
mixin LangMixin<T extends StatefulWidget> on State<T> {
  @override
  void initState() {
    super.initState();
    LanguageService().addListener(_rebuildOnLang);
  }

  @override
  void dispose() {
    LanguageService().removeListener(_rebuildOnLang);
    super.dispose();
  }

  void _rebuildOnLang() {
    if (mounted) setState(() {});
  }
}
